#!/usr/bin/env python3
"""
masumi-agent - Main Entry Point
Generated by masumi init

This is the entry point for your Masumi agent.
Run this file to start the agent server.
"""

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

from masumi import run
from agent import process_job

# Define input schema - Sokosumi format
INPUT_SCHEMA = {
    "input_data": [
        {
            "id": "prospect_name",
            "type": "text",
            "name": "Prospect Name",
            "data": {
                "placeholder": "Enter prospect's full name",
                "description": "Full name of the prospect"
            },
            "validations": [
                {"validation": "min", "value": "2"},
                {"validation": "max", "value": "100"}
            ]
        },
        {
            "id": "prospect_email",
            "type": "email",
            "name": "Prospect Email",
            "data": {
                "placeholder": "prospect@company.com",
                "description": "Email address of the prospect"
            },
            "validations": [
                {"validation": "format", "value": "email"}
            ]
        },
        {
            "id": "prospect_role",
            "type": "text",
            "name": "Prospect Role",
            "data": {
                "placeholder": "e.g., VP of Sales",
                "description": "Job title or role of the prospect"
            },
            "validations": [
                {"validation": "min", "value": "2"},
                {"validation": "max", "value": "100"}
            ]
        },
        {
            "id": "company_name",
            "type": "text",
            "name": "Company Name",
            "data": {
                "placeholder": "Enter company name",
                "description": "Name of the prospect's company"
            },
            "validations": [
                {"validation": "min", "value": "2"},
                {"validation": "max", "value": "100"}
            ]
        },
        {
            "id": "company_industry",
            "type": "text",
            "name": "Company Industry",
            "data": {
                "placeholder": "e.g., Technology, Healthcare",
                "description": "Industry sector of the company"
            },
            "validations": [
                {"validation": "min", "value": "2"},
                {"validation": "max", "value": "50"}
            ]
        },
        {
            "id": "company_size",
            "type": "option",
            "name": "Company Size",
            "data": {
                "description": "Size of the company",
                "values": ["startup", "small", "medium", "large", "enterprise"]
            },
            "validations": [
                {"validation": "min", "value": "1"},
                {"validation": "max", "value": "1"}
            ]
        },
        {
            "id": "intent_signal",
            "type": "option",
            "name": "Intent Signal Type",
            "data": {
                "description": "Type of intent signal detected",
                "values": [
                    "job_change",
                    "funding_event",
                    "technology_adoption",
                    "company_growth",
                    "industry_trend"
                ]
            },
            "validations": [
                {"validation": "min", "value": "1"},
                {"validation": "max", "value": "1"}
            ]
        },
        {
            "id": "intent_description",
            "type": "text",
            "name": "Intent Description",
            "data": {
                "placeholder": "Describe the intent signal",
                "description": "Detailed description of the intent signal"
            },
            "validations": [
                {"validation": "min", "value": "10"},
                {"validation": "max", "value": "500"}
            ]
        }
    ]
}

# Schema handler - returns plain dict for Masumi SDK
def get_schema():
    return INPUT_SCHEMA

# Main entry point
if __name__ == "__main__":
    run(
        start_job_handler=process_job,
        input_schema_handler=get_schema
    )
